// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleManagement.Infrastructure.Persistence;

#nullable disable

namespace VehicleManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928060959_UpdateCategoryIcons")]
    partial class UpdateCategoryIcons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleManagement.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Holden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Volvo"
                        });
                });

            modelBuilder.Entity("VehicleManagement.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("VehicleManagement.Domain.Entities.VehicleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MaxWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "light_icon",
                            MaxWeight = 500m,
                            MinWeight = 0m,
                            Name = "Light"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "medium_icon",
                            MaxWeight = 2500m,
                            MinWeight = 500m,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "heavy_icon",
                            MinWeight = 2500m,
                            Name = "Heavy"
                        });
                });

            modelBuilder.Entity("VehicleManagement.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("VehicleManagement.Domain.Entities.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
